### ISSUE TITLE
Blog Post Suggestion: Multi TB time series dataset -> Image processing -> video 

### ISSUE THREAD

**Issue by alex-rakowski** [dask/dask-blog#100]
I have a use case where I collect multiple TB datasets (electron microscopy) time series videos. The image processing requires a combination of resizing (e.g. 4k ->1k xy or time-averaging frames), various filtering steps, background subtraction, and image alignment. Some of these steps can be performed by only considering an individual frame, others require using neighboring frames etc. After the processing, the images are typically rendered to video, and/or processed programmatically. Currently, a lot of this is performed using proprietary software, which is limited in its capabilities and slow. 

It would be great to create an open-source repo for analysing these sorts of datasets, underpinned by Dask. I've written a basic workflow, which with a bit of polish and some assistance,  I thought could be the basis of a blog post, and would be a great spot for me to start a repo from. 

The blog post would demonstrate:
- reading image files with a custom file reader (file reader already written)
- video writing with FFMPEG from dask array/dask delayed list. 
- how to handle working with individual frames and multiple frames, implications on chunksize 
- demonstrating custom user functions.
- workflow which scales from laptop to HPC (I have access to HPC compute time)
- would be great to include examples gpu accelerated image processing steps. 

might be a bit too similar to:
- https://blog.dask.org/2019/06/20/load-image-data
- https://blog.dask.org/2021/03/19/image-segmentation

**Comment by jacobtomlinson** [comment]
This sounds great and you should definitely write a blog post about it. I wouldn't be too concerned about being similar to other posts.

I think the best way to get started would be to throw a rough draft up in a Pull Request. If you're after some assistance it would be great if you could write up some actionable tasks that you need help with and we can find the right folks.

If you're interested in GPU acceleration there may also be interest in writing a follow-up post on the RAPIDS blog. In any case it would be interesting to chat more about what you're doing here. cc @quasiben

**Comment by dmilkie** [comment]
I've been curious what are best practices (and what are the best tools) to orchestrate a whole image processing pipeline (and make it flexible enough that others could add/adapt/hack to make it better).  There is a whole set of problems  to consider (big TB data, saving intermediates, dependencies, fanning out different steps to cluster, metadata continuity, what to retain in memory/vs disk, ....).  If you have any expertise on any of that, I'd at least be interested.

**Comment by GenevieveBuckley** [comment]
Hi @alex-rakowski, have you thought any more about writing this?

It sounds like it'd be an awesome blogpost. Definitely don't worry about whether it's similar or not to other posts, we love seeing these kinds of variations. I bet a lot of other people would find it really useful, too.

**Comment by jacobtomlinson** [comment]
Given that there has been no follow up from @alex-rakowski for 12 months I'm going to close this out. Would be great to see a post like this though!
