### ISSUE TITLE
Mosaic image fusion blogpost - add a link to Tobias' project in the "Also see" section?

### ISSUE THREAD

**Issue by GenevieveBuckley** [dask/dask-blog#125]
@VolkerH I saw [you added a small note](https://github.com/VolkerH/DaskFusion/commit/f0705c12d810432659c26592b540dd25b82cdf10) to the [DaskFusion](https://github.com/VolkerH/DaskFusion) README that links to Tobias' project. 

Should I do the same in the blogpost under the "Also see" section heading at the bottom? They each focus on slightly different things, so it might be helpful for people.

https://twitter.com/TobiasAdeJong/status/1466719789280382977

```
Some [feedback on the blog post](https://twitter.com/TobiasAdeJong/status/1466719789280382977) by [Tobias deJong](https://github.com/TAdeJong) points out a very similar approach that allows incorporates optimization of tile positions, [see this notebook](https://github.com/TAdeJong/LEEM-analysis/blob/master/6%20-%20Stitching.ipynb). 
```

**Comment by VolkerH** [comment]
I'm not sure.

I found Tobias's notebook interesting, but it is much more application specific and doesn't explain the dask aspects. 
I tend towards not including the link in the dask blog post, where the audience is presumably more interested in what they can do with dask.

Those who actually need to fuse/stitch large collections of tiles (e.g. who may be interested in the specifics of the application) will probably also look at the DaskFusion repo and find the link in the  README.

Ultimately, I'll leave the choice up to you.

**Comment by GenevieveBuckley** [comment]
> I found Tobias's notebook interesting, but it is much more application specific and doesn't explain the dask aspects. I tend towards not including the link in the dask blog post, where the audience is presumably more interested in what they can do with dask.
> 
> Those who actually need to fuse/stitch large collections of tiles (e.g. who may be interested in the specifics of the application) will probably also look at the DaskFusion repo and find the link in the README.

That makes sense, ok then!
