### ISSUE TITLE
Blogpost idea: Understanding meta

### ISSUE THREAD

**Issue by jsignell** [dask/dask-blog#129]
I am not sure this belongs as a blogpost, but I have been including a bit about meta in some talks that I have been doing and there are some recurring questions that come up on the issue tracker that make it clear that the concept of meta is not well understood. 

Basically I'd just be expanding on this comment: https://github.com/dask/dask/issues/8515#issuecomment-1000450648

**Comment by jsignell** [comment]
and this one: https://github.com/dask/dask/issues/8537#issuecomment-1011229566

**Comment by jsignell** [comment]
and another one https://github.com/dask/dask/issues/8579

**Comment by pavithraes** [comment]
Thanks for opening this, Julia! I think it's an excellent idea, and definitely needed. I'm going to try drafting a post. :)

**Comment by jacobtomlinson** [comment]
The draft is looking great @pavithraes. Do you think you could submit this here at some point soon?

**Comment by pavithraes** [comment]
> The draft is looking great @pavithraes. Do you think you could submit this here at some point soon?

@jacobtomlinson Thank you, and yes! I was on vacation last week, getting back to this today. :)

**Comment by jacobtomlinson** [comment]
Hope you had a good vacation!

**Comment by GenevieveBuckley** [comment]
Linking to [this comment](https://github.com/dask/dask/issues/7589#issuecomment-1172903442) since it seems related. If there's a way the blogpost could use something similar as an example, that would be a very useful thing to include.

(If I've misunderstood & this isn't actually relevant, ignore me)
