### ISSUE TITLE
Add tags metadata to blogposts

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-blog#133]
Hi Folks, currently it looks like we currently track tags in each of the markdown files for each blogpost, but we don't expose these in the HTML or XML/RSS/Atom feeds.  

We're currently trying to migrate over our blog to a new platform and it would be useful to have these in the RSS/Atom feeds, even if they're not visible anywhere.  

Does anyone have time to add this?  At minimum it would probably mean looking up what approach people use by default, and then editing https://github.com/dask/dask-blog/blob/gh-pages/atom.xml or the layouts directory to include tags somewhere.  (Grepping for tags yields some interesting results)

@jacobtomlinson is this easy for you or someone around you?

**Comment by jacobtomlinson** [comment]
Looks like there is no convention for tags, but there is a `<category>` that has similar functionality.

https://www.w3schools.com/xml/xml_rss.asp

Poking around some popular blogs they seem to use this category metadata in the way we are using tags.
