### ISSUE TITLE
Any interest in a blog post on dask-memusage?

### ISSUE THREAD

**Issue by itamarst** [dask/dask-blog#20]
dask-memusage is tool I wrote that gives you max memory usage per task in the executed graph, so you can:

1. Focus memory optimization efforts.
2. Configure parallelism to maximize cores when memory usage is the hardware bottleneck.

https://github.com/itamarst/dask-memusage/

Happy to write a blog post if you're interested.

**Comment by GenevieveBuckley** [comment]
I've recently been talking with user groups who are asking for better/easier ways to get an overview and optimize dask operations, so I'd say there's some interest out there for a blogpost.

**Comment by jacobtomlinson** [comment]
Looks like a neat package. I'm sure a blog post would be appreciated.

**Comment by itamarst** [comment]
Cool, I'll add it to my todo list.

**Comment by itamarst** [comment]
> I've recently been talking with user groups who are asking for better/easier ways to get an overview and optimize dask operations, so I'd say there's some interest out there for a blogpost.

Sorry I missed this, BTW, got buried in my email I guess. More recently than dask-memusage I also wrote an open source memory profiler (https://pythonspeed.com/products/filmemoryprofiler/) since existing tools don't work well for the sort of use cases Dask is for. So that might also be helpful for some people, and I'll probably at least mention it in anything I write as a natural next step once specific tasks have been pinpointed.

(I am also working on a commercial version that will hopefully be fast enough for production workloads, so people can have always-on memory profiling, ping me itamar@pythonspeed.com if you're interested in hearing more.)
