### ISSUE TITLE
Blogpost on loading TIF data into a Dask array

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-blog#26]
It would be handy to have a blogpost about loading image data into Dask Array, and then possibly storing it into some other format, like HDF5 or Zarr. 

It might be nice to have both a trivial example here (a simple stack of images), as well as a less-trivial example (if those are common).

cc @jakirkham , perhaps the world's leading expert

**Comment by jakirkham** [comment]
Thanks for opening this. Yep, happy to write this. Also happy to have it here if it makes sense. I did chuckle a bit when you said "leading expert". 😄

**Comment by jakirkham** [comment]
Added PR ( https://github.com/dask/dask-blog/pull/30 ). Still very rough, but open to molding it as needed.
