### ISSUE TITLE
Single GPU CuPy Benchmark Post not listed on blog index

### ISSUE THREAD

**Issue by mmccarty** [dask/dask-blog#41]
I just noticed that the [single-gpu-cupy-benchmarks](https://blog.dask.org/2019/06/27/single-gpu-cupy-benchmarks) blog post is not listed on the blog [index](https://blog.dask.org/).  Can someone add it?  Thanks!

**Comment by mrocklin** [comment]
I think that we're planning to release it on the RAPIDS Medium blog first.
What's up there is currently a draft.

**Comment by mmccarty** [comment]
Okay, thanks!
