### ISSUE TITLE
Should I include RAPIDS posts here?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-blog#7]
So I just pushed out http://matthewrocklin.com/blog/work/2019/01/03/dask-array-gpus-first-steps which I think would be a great post to include here as well, except that at the end I say "come work for NVIDIA" which is a bit corporate.  Should we include this post on blog.dask.org as well?  Some options: 

1.  Yes, as long as things like this are at the end and tasteful then yes, we invite posts with an agenda (in this case, recruitment)
2.  Yes, but please remove the "come work for NVIDIA" bit on our version of it
3.  No, it's already posted elsewhere, no need to cross post here
4.  ...

Thoughts or objections?

**Comment by TomAugspurger** [comment]
No objections to including it here. People working anywhere on dask-related things seems good for the project, so I'm not bothered by the recruiting section.
