### ISSUE TITLE
What syntax do I need for links in a table of contents?

### ISSUE THREAD

**Issue by GenevieveBuckley** [dask/dask-blog#90]
Clicking the links in the table of contents [in this blogpost](https://blog.dask.org/2021/03/04/the-life-science-community) doesn't take you to the corresponding section of the post, but it does work [if you do it here](https://github.com/dask/dask-blog/blob/gh-pages/_posts/2021-03-04-the-life-science-community.md).

Did I get the syntax for this wrong? Or is jekyll somehow losing these markers when it renders things?

This is what I used as my markdown syntax:

```
## Contents
* [Background](#Background)
* [What we learned](#What-we-learned)
    * [From Dask users](#From-Dask-users)
    * [From other software libraries](#From-other-software-libraries)
* [Opportunities we see](#Opportunities-we-see)
* [Strategic plan](#strategic-plan)
* [Limitations](#Limitations)
* [Methods](#Methods)
* ```

**Comment by mrocklin** [comment]
I'll admit to also being curious about how to do this :)

**Comment by stsievert** [comment]
Does un-capitalizing the leading letters help?

``` diff
- * [Background](#Background)
+ * [Background](#background)
```

Entering https://blog.dask.org/2021/03/04/the-life-science-community#background into my URL bar navigates to the "Background" header for me.

**Comment by stsievert** [comment]
Whoops – I made some typos in https://github.com/dask/dask-blog/issues/90#issuecomment-824140984, and have fixed them now.

**Comment by GenevieveBuckley** [comment]
Hey, I think that's the fix! Thank you @stsievert

**Comment by GenevieveBuckley** [comment]
I think this is the list of rules for internal hyperlinks with jekyll:
* Replace all spaces with hyphens
* Make all letters lowercase
* Remove punctuation characters (like colons)
